export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const GET_ORDERS = "GET_ORDERS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const VISITOR_TO_CART = "VISITOR_TO_CART";
export const VISITOR_ADD_ITEM_TO_CART = "VISITOR_ADD_ITEM_TO_CART";
export const VISITOR_REMOVE_ITEM_FROM_CART = "VISITOR_REMOVE_ITEM_FROM_CART";
export const LOGOUT = "LOGOUT"
export const RESETORDER = "RESETORDER"
export const CARTMESSAGE = "CARTMESSAGE"
export const CLEARCARTMESSAGE = "CLEARCARTMESSAGE"
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const SEARCH_FEATURES = "SEARCH_FEATURES";



